services:
  plutchart-api:
    image: plutchart-api:1
    container_name: plutchart-api
    build: ./api
    restart: always
    env_file:
      - path: ./api/.env
        required: true
      - path: ./api/.env.development.local
        required: false
    environment:
      - PORT=8000
  
  plutchart-landing:
    image: plutchart-landing:1
    build: ./landing
    container_name: plutchart-landing
    environment:
      - PORT=3001

  plutchart-tool:
    image: plutchart-tool:1
    build: ./tool
    container_name: plutchart-tool
    environment:
      - PORT=3002
  plutchart-wiki:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: plutchart-wiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- DB_TYPE=sqlite #optional
      #- DB_HOST= #optional
      #- DB_PORT= #optional
      #- DB_NAME= #optional
      #- DB_USER= #optional
      #- DB_PASS= #optional
    volumes:
      - ./wiki/config:/config
      - ./wiki/data:/data
    restart: unless-stopped