services:
  web:
    image: nginx:1
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - nginx-logs:/var/log/nginx/services/:rw
  #certbot:
  #  image: certbot/certbot:latest
  #  container_name: certbot
  #  volumes:
  #    - ./certbot/www/:/var/www/certbot/:rw
  #    - ./certbot/conf/:/etc/letsencrypt/:rw

  api:
    image: api:1
    container_name: api
    restart: always
    depends_on: 
      - mongo
    env_file:
      - path: ./api/.env
        required: true
      - path: ./api/.env.development.local
        required: false
    environment:
      - PORT=8000
  
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-volume:/data/db/:rw

  landing:
    image: landing:1
    container_name: landing
    environment:
      - PORT=3001

  tool:
    image: tool:1
    container_name: tool
    environment:
      - PORT=3002

volumes:
  mongo-volume:
    name: mongo-volume
    external: true
  nginx-logs:
    name: nginx-logs
    external: true

